import html
import random

html = """
<h1>Hello</h1>
<p>This was generated by Python</p>
"""

print(html)

import pygame
import random

pygame.init()

width = 500
height = 700
screen = pygame.display.set_mode((width, height))
pygame.display.set_caption("Alien Shooter Mobile")

black = (0, 0, 0)
white = (255, 255, 255)
green = (0, 255, 0)
red = (255, 0, 0)
blue = (0, 100, 255)

player = pygame.Rect(220, 600, 60, 30)

bullet = pygame.Rect(0, 0, 5, 10)
bullet_active = False

alien = pygame.Rect(random.randint(0, 460), 0, 40, 40)

clock = pygame.time.Clock()
running = True

# Buttons (x, y, radius)
left_btn = (80, 650, 40)
right_btn = (180, 650, 40)
shoot_btn = (420, 650, 40)

while running:
    clock.tick(60)
    screen.fill(black)

    for event in pygame.event.get():
        if event.type == pygame.QUIT:
            running = False

        if event.type == pygame.MOUSEBUTTONDOWN:
            mx, my = pygame.mouse.get_pos()

            # Left button
            if (mx - left_btn[0])**2 + (my - left_btn[1])**2 <= left_btn[2]**2:
                player.x -= 20

            # Right button
            if (mx - right_btn[0])**2 + (my - right_btn[1])**2 <= right_btn[2]**2:
                player.x += 20

            # Shoot button
            if (mx - shoot_btn[0])**2 + (my - shoot_btn[1])**2 <= shoot_btn[2]**2:
                if not bullet_active:
                    bullet.x = player.x + 27
                    bullet.y = player.y
                    bullet_active = True

    # Keep player inside screen
    if player.x < 0:
        player.x = 0
    if player.x > 440:
        player.x = 440

    # Move bullet
    if bullet_active:
        bullet.y -= 7
        if bullet.y < 0:
            bullet_active = False

    # Move alien
    alien.y += 3
    if alien.y > 700:
        alien.x = random.randint(0, 460)
        alien.y = 0

    # Collision
    if bullet_active and alien.colliderect(bullet):
        alien.x = random.randint(0, 460)
        alien.y = 0
        bullet_active = False

    # Draw objects
    pygame.draw.rect(screen, green, player)
    pygame.draw.rect(screen, white, bullet)
    pygame.draw.rect(screen, red, alien)

    # Draw buttons
    pygame.draw.circle(screen, blue, (left_btn[0], left_btn[1]), left_btn[2])
    pygame.draw.circle(screen, blue, (right_btn[0], right_btn[1]), right_btn[2])
    pygame.draw.circle(screen, red, (shoot_btn[0], shoot_btn[1]), shoot_btn[2])

    pygame.display.update()

pygame.quit()